# Generated by Django 5.2.1 on 2025-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
